### PR TITLE
Fix to broken debian stable package xdg-desktop-menu

### PR DESCRIPTION
**Pull request by zalox**
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=730621

### CODE REVIEW

**Comment by zalox** [comment]
Sending it here since it will mess up my work.

**Comment by eidheim** [comment]
Are you sure this is needed? It worked on my Debian stable. The juci.desktop file is installed in /usr/share/applications/

**Comment by eidheim** [comment]
Only works though when doing `sudo make install`

**Comment by zalox** [comment]
Yes, this is needed. A lot of Debian packages has made their own fix to this problem. If you already have one of those installed, the problem wont occur.

**Pull request merged**
